Update site to solar
badgerloop-software/website-condor pull request #30
Opened 2022-01-27 17:37 UTC by meganchoy

Most to all major changes are complete. 

The only thing left to do - that is not a huge deal - is updating the silhouette on the footer

2022-01-29 21:10 UTC, LukeHouge approved these changes
Looks good, thanks for getting this updated!

I am going to edit the text in the timeline and update the sponsors, and then if you could take a look at the stats not loading it should be good to go.

2022-01-30 18:02 UTC, EUdds requested changes

2022-01-30 18:02 UTC, EUdds commented on public/contact.html
> +		content="Badgerloop is a student organization at the University of Wisconsin-Madison that competes in the SpaceX Hyperloop Pod Competition" />
Same

2022-01-30 18:02 UTC, EUdds commented on public/error.html
>  		content="Badgerloop is a student organization at the University of Wisconsin-Madison that competes in the SpaceX Hyperloop Pod Competition" />
Same

2022-01-30 19:18 UTC, EUdds approved these changes

2022-02-03 17:16 UTC, meganchoy commented on public/about-badgerloop.html
> +    <meta name="description" content="Badgerloop is a student organization at the University of Wisconsin-Madison that competes in the SpaceX Hyperloop Pod Competition">
see new commits

2022-02-03 17:40 UTC, LukeHouge commented on public/index.html
> +      content="Badgerloop is a student organization at the University of Wisconsin-Madison that competes in the American Solar Chalelnge"
can you fix this spelling on all these meta tags?

2022-02-04 18:11 UTC, merged